// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcktvnykdncsnqnxbfnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indja3R2bnlrZG5jc25xbnhiZm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDM5MTYsImV4cCI6MjA2NjY3OTkxNn0.QgsboNCFBRFJskdrw6GRDFFdmc08fSgx_Co0K96p11Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);